### ISSUE TITLE
Blob is not defined in SSR

### ISSUE THREAD

**Issue by chrisands** [chrisguttandin/standardized-audio-context#447]
Hi!

I'm getting this error on when trying import AudioContext

```
/workspace/node_modules/async-array-buffer/build/es5/bundle.js:10
    var blob = new Blob([worker], {
               ^

ReferenceError: Blob is not defined
    at /workspace/node_modules/async-array-buffer/build/es5/bundle.js:10:13
    at /workspace/node_modules/async-array-buffer/build/es5/bundle.js:2:65
    at Object.<anonymous> (/workspace/node_modules/async-array-buffer/build/es5/bundle.js:5:2)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Module._compile (/workspace/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.newLoader [as .js] (/workspace/node_modules/pirates/lib/index.js:88:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
error Command failed with exit code 1.
```

It [happens because Node.js doesn't have Blob](https://stackoverflow.com/questions/53637644/how-do-i-create-a-blob-in-node-js).
I think is it possible to add check, when it tries to run not in browser?

`standardized-audio-context v17.5.7`

**Comment by chrisands** [comment]
Thank you answer!
I used dynamic import with window check to get it work
const { AudioContext } = await import('standardized-audio-context')

**Comment by chrisands** [comment]
Thank you for answer! 

It worked for me, i used dynamic import (ES6 feature) with babel plugin to get it work:
```
if (typeof window !== 'undefined') { 
  const { AudioContext } = await import('standardized-audio-context')
}
```
