### ISSUE TITLE
channelData can be null in

### ISSUE THREAD

**Issue by JackCA** [chrisguttandin/standardized-audio-context#795]
I'm (rarely) getting the following exception in the audio context constructor:

```
TypeError: Cannot set property '0' of null
  at ? (/app/node_modules/standardized-audio-context/build/es2018/helpers/test-audio-node-disconnect-method-support.js:8:1)
  at new Promise(<anonymous>)
  at testAudioNodeDisconnectMethodSupport(/app/node_modules/standardized-audio-context/build/es2018/helpers/test-audio-node-disconnect-method-support.js:2:1)
  at test(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-node-constructor.js:272:24)
  at cacheTestResult(/app/node_modules/standardized-audio-context/build/es2018/factories/cache-test-result.js:12:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-node-constructor.js:271:1)
  at new <anonymous>(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-destination-node-constructor.js:10:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/minimal-base-audio-context-constructor.js:13:1)
  at super(/app/node_modules/standardized-audio-context/build/es2018/factories/base-audio-context-constructor.js:4:1)
  at new <anonymous>(/app/node_modules/standardized-audio-context/build/es2018/factories/audio-context-constructor.js:21:1)
```

The only pattern I can see is that it only has happened in chrome. [Here is a public link to the Sentry event ](https://sentry.io/share/issue/4d8314c84afd463d9313d9f44fbf5e17/)(clicking `Full` on the top right will give line context).

**Comment by chrisguttandin** [comment]
Thanks for reporting this, Jack. It's very weird though. The error says that `channelData` is `null` on that [line](https://github.com/chrisguttandin/standardized-audio-context/blob/master/src/helpers/test-audio-node-disconnect-method-support.ts#L14).

I couldn't reproduce it so far. Is it specific to a certain version of Chrome or an operating system?

**Comment by JackCA** [comment]
Here's all of the occurences history:

![image](https://user-images.githubusercontent.com/296167/72212693-80915100-3495-11ea-87a2-dd533ec556e1.png)

**Comment by chrisguttandin** [comment]
I still can't make any sense of the error message but it should at least not throw an unhandled error anymore. If it happens again the error will be catched and interpreted as if the tested feature is not supported.

The changes should not cause any difference in the behavior. Please let me know if the error still shows up in your logs with v23.1.2 or later.

**Comment by JackCA** [comment]
@chrisguttandin awesome. I deployed v23.1.1 and will monitor it.

Thank you! 🙏
